### ISSUE TITLE
install cairo-nile and run make in docker build

### ISSUE THREAD

**Issue by NiklasTR** [tohrnii/openlab-cairo#3]
```
# TODO install cairo-nile and run make
```

https://github.com/labdao/openlab-cairo/blob/7b5f397205e360ef918ad69745789baf47161789/Dockerfile#L15

**Comment by tohrnii** [comment]
Fixed: https://github.com/labdao/openlab-cairo/commit/a08b7017c5e4a5717c7709405ecc66f022ea73a6

**Comment by tohrnii** [comment]
Fixed with https://github.com/labdao/openlab-cairo/commit/6801015a1baaac3534dfdf8b9ca4e366b640b3d0
